### ISSUE TITLE
Extra zeros at the end of files with FUSE

### ISSUE THREAD

**Issue by mkroening** [hermit-os/kernel#1111]
This program

```rust
fn main() {
    std::fs::write("/root/test.txt", "important content").unwrap();
}
```

writes extra zeros to the end of the file:

```console
$ od -t x1 foo/test.txt 
0000000 69 6d 70 6f 72 74 61 6e 74 20 63 6f 6e 74 65 6e
0000020 74 00 00 00 00 00 00 00
0000030
```

expected:

```console
$ od -t x1 foo/test.txt 
0000000 69 6d 70 6f 72 74 61 6e 74 20 63 6f 6e 74 65 6e
0000020 74
0000021
```

Bisecting fails since not all of https://github.com/hermit-os/kernel/pull/1047 's commits compile!

```
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
a2212c010250c69ce581a9459683ae14a7b963ef
fbb5789508286aa5a019f8b9e5371c3ecbf108d2
24c425b5e825ca5e2c91bdd863df9b5cdf33717f
3a93d4a843fa9e9af340ff4432f461265d90f508
f13bf48f06817a2a44f5dc903f4cd8ac8163fe2a
We cannot bisect more!
```

- a2212c010250c69ce581a9459683ae14a7b963ef
- fbb5789508286aa5a019f8b9e5371c3ecbf108d2
- 24c425b5e825ca5e2c91bdd863df9b5cdf33717f
- 3a93d4a843fa9e9af340ff4432f461265d90f508
- f13bf48f06817a2a44f5dc903f4cd8ac8163fe2a

This can be replicated by editing `hello_world` in hermit-rs and running

```console
cargo xtask ci qemu --arch x86_64 --profile dev --package hello_world --virtiofsd
```

CC: @cagatay-y

**Comment by cagatay-y** [comment]
I think we were not testing FUSE except for initialization. When I set the log level for virtiofsd to trace and ran the rusty_demo test, I got no trace output and no file was created in the shared directory. However, when I changed the path provided in the test from "/tmp/foo.txt" to "/root/foo.txt" in [rusty_demo](https://github.com/hermit-os/hermit-rs/blob/32c9470b5bbb67022c7853cc54e146f62ab8ec12/examples/demo/src/tests/mod.rs#L131) ("/root" is the mount point [logged](https://github.com/hermit-os/kernel/actions/runs/8435082828/job/23099700906#step:13:137) during the initialization), I got log output for file creation, a file in the shared directory and a crash during the file read.

Also, [it seems like](https://github.com/hermit-os/kernel/actions/runs/8435082828/job/23099701139#step:13:130) the test is broken for the release build and the driver cannot be initialized. This is not the case with the debug build. We probably did not notice that because FUSE was bypassed.
