### ISSUE TITLE
Async Tasks: already borrowed

### ISSUE THREAD

**Issue by mkroening** [hermit-os/kernel#846]
On a recent dependency upgrade (https://github.com/hermitcore/libhermit-rs/commit/6d1cc40a8919cb1a4ccd253928ee3c053a5765d3), we had this: https://github.com/hermitcore/libhermit-rs/actions/runs/5860477602/job/15888622599:

```
$ qemu-system-aarch64 -semihosting \
    -kernel rusty-loader-aarch64 -machine virt,gic-version=3 \
    -m 512M -cpu cortex-a72 -smp 1 -display none -serial stdio \
    -device guest-loader,addr=0x48000000,initrd=target/aarch64-unknown-hermit/release/httpd \
    -netdev user,id=u1,hostfwd=tcp::9975-:9975,net=192.168.76.0/24,dhcpstart=192.168.76.9 \
    -device virtio-net-pci,netdev=u1,disable-legacy=on &
    sleep 5
    curl http://127.0.0.1:9975/help
    sleep 1
[...]
[0][INFO] DNS server 0:    192.168.76.3
[0][WARN] Unable to read entropy! Fallback to a naive implementation!
Now listening on port 9975
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

[0][PANIC] panicked at 'already borrowed: BorrowMutError', src/arch/aarch64/kernel/core_local.rs:72:34
[0][INFO] Number of interrupts
[0][INFO] [0][Reschedule]: 8
[0][INFO] [0][Timer]: 1
[0][INFO] [0][virtio_net]: 8
[0][INFO] Shutting down system
```

which is https://github.com/hermitcore/libhermit-rs/blob/a12db435f4a816a88ef419a0476072cb8d4b2cd2/src/arch/aarch64/kernel/core_local.rs#L71-L73

CC: @stlankes

**Comment by egrimley-arm** [comment]
I've seen the same error, I think. I get it with a trivial server that only writes, like this:

Test program Cargo.toml:
```
[package]
name = "testtcp"
version = "0.1.0"
edition = "2021"

[dependencies]

[target.'cfg(target_os = "hermit")'.dependencies.hermit]
path = "../rusty-hermit/hermit"
```

Test program src/main.rs:
```
#[cfg(target_os = "hermit")]
use hermit as _;

use std::io::Write;
use std::net::TcpListener;

fn main() {
    let listener = TcpListener::bind("127.0.0.1:8080").unwrap();
    loop {
        println!("about to accept");
        let (mut socket, _addr) = listener.accept().unwrap();
        let n = 300;
        println!("about to write_all {n} times");
        for _ in 0..n {
            socket.write_all(b"\n").unwrap();
        }
    }
}
```

`rusty-hermit` is at 71f85cfcd04a733f380968f429a35d51fbf749f5
`rusty-hermit/kernel` is at 012430a9ad1f01dcc55616916dcb23752c43baab

Build and run with Hermit on AArch64:
```
cargo build --target aarch64-unknown-hermit \
  -Z build-std=std,core,alloc,panic_abort \
  -Z build-std-features=compiler-builtins-mem

qemu-system-aarch64 \
    -machine virt,gic-version=3 \
    -cpu cortex-a72 -smp 1 -m 512M  \
    -display none -serial stdio \
    -kernel ../rusty-loader/target/aarch64/release/rusty-loader \
    -device guest-loader,addr=0x48000000,initrd=target/aarch64-unknown-hermit/debug/testtcp \
    -netdev user,id=u1,hostfwd=tcp::8080-:8080 \
    -device virtio-net-pci,netdev=u1,disable-legacy=on
```

Test from another terminal:
```
while socat -u TCP:localhost:8080 CREATE:out ; do : ; done &
```

I find usually about 5 connections are accepted before one of the following things happen:

* The server hangs after printing `about to write_all 300 times`.
* There is the following error:
```
about to write_all 300 times
[0][PANIC] panicked at src/arch/aarch64/kernel/core_local.rs:90:34:
already borrowed: BorrowMutError
```

On Intel I see no such problems, and there's also this observation, which seems that it might be relevant: **on Intel it runs about 40 times faster** (and not because of KVM acceleration: I get `Permission denied` if I try to use `-enable-kvm`).

This is how I built and ran on Intel for the comparison:
```
cargo build --target x86_64-unknown-hermit --release \
  -Z build-std=std,core,alloc,panic_abort \
  -Z build-std-features=compiler-builtins-mem

qemu-system-x86_64 \
    -cpu qemu64,apic,fsgsbase,fxsr,rdrand,rdtscp,xsave,xsaveopt \
    -smp 1 -m 512M \
    -device isa-debug-exit,iobase=0xf4,iosize=0x04 \
    -display none -serial stdio \
    -kernel ../rusty-loader/target/x86_64/release/hermit-loader \
    -initrd target/x86_64-unknown-hermit/release/testtcp \
    -netdev user,id=u1,hostfwd=tcp::8080-:8080 \
    -device virtio-net-pci,netdev=u1,disable-legacy=on
```

**Comment by egrimley-arm** [comment]
There seems to be a reentrant call to `executor::run()`. I don't suppose there's any easy way of getting a backtrace?

**Comment by mkroening** [comment]
Thank you so much for reproducing! I can get back traces using GDB. I'll have a quick try at reproducing later. :)

**Comment by mkroening** [comment]
I won't be able to look into this today, but at least I documented how to use GDB: https://github.com/hermit-os/loader/pull/267

Hopefully, this somewhat fits your expectation of easy. ^^

**Comment by egrimley-arm** [comment]
> I won't be able to look into this today, but at least I documented how to use GDB: [hermit-os/loader#267](https://github.com/hermit-os/loader/pull/267)

Thanks. I'm getting some backtraces with that recipe.

(I've just deleted what I wrote before about it running much more slowly on AArch64: I was making the obvious mistake of comparing `debug` with `release`! In fact it's only about 1.4x slower on AArch64.)

**Comment by mkroening** [comment]
> In fact it's only about 1.4x slower on AArch64.

That's a relief. 😅

**Comment by egrimley-arm** [comment]
I'm a bit suspicious of this because I thought that one would set the bits to 1 to disable interrupts:
https://github.com/hermit-os/hermit-sync/blob/77c63e821c85287e89450ffd78f90e92596a90e0/src/interrupts.rs#L93

However, changing that `0` to `0xF` or `0xFFFFFFFFFFFFFFFF` makes no difference to the behaviour. Can we check somehow whether `hermit_sync::without_interrupts` is working on AArch64?

**Comment by egrimley-arm** [comment]
Correction: changing the value of `DISABLE` from `0` to `0xFFFFFFFFFFFFFFFF` does seem to fix this problem! Today I will experiment a bit further and check exactly which bits should be set. (Perhaps the correct value should be 0x3c0?)

(Yesterday evening I thought the change didn't help because there is a bug in the build system: a change to that file, `interrupts.rs`, doesn't get detected when you run `cargo build`. Perhaps that can be fixed in `build.rs` somewhere?)

**Comment by mkroening** [comment]
Thanks a lot for your investigation! I'll quickly cook up a PR.

If you modified the file in `$HOME/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hermit-sync-0.1.3/src/lib.rs`, then it's expected that this is not automatically picked up by Cargo. These paths should usually not be touched, as they are meant to contain the exact source code of the respective release. For local development, the usual way is to modify the kernel's `Cargo.toml` to point the dependency to a local path. That path is then automatically watched for changes.

**Comment by egrimley-arm** [comment]
I modified `rusty-hermit/kernel/Cargo.toml` to have `hermit-sync = { path = "../../hermit-sync" }` and the change to `interrupts.rs` didn't seem to be detected. Perhaps I'll investigate that a bit further. I would have thought that this line should handle it somehow:
https://github.com/stlankes/hermit-rs/blob/71f85cfcd04a733f380968f429a35d51fbf749f5/hermit/build.rs#L133
(Yes, that's the version of `rusty-hermit` I'm using at the moment; not sure if I should be.)

**Comment by mkroening** [comment]
Ah, yes. That makes sense.

So the kernel build would pick that up, but the kernel build is never triggered from the wrapper crate. I am not sure what's the best solution here because _always_ triggering a kernel rebuild seems undesirable, even if it does not take that long. We might scan the kernel's `Cargo.toml` and add any `path` dependencies explicitly.

On the other hand, maybe https://github.com/hermit-os/hermit-rs/pull/471 fixed the annoying rebuilds and we can just call kernel build always. Let me check.

**Comment by mkroening** [comment]
Makes sense. I opened https://github.com/hermit-os/hermit-rs/issues/472.
